# Generated by Django 6.0.4 on 2026-05-07 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'actualité")),
                ('contenu', models.TextField(verbose_name='Contenu détaillé')),
                ('image', models.ImageField(blank=True, null=True, upload_to='actualites/', verbose_name="Image d'illustration")),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
            ],
            options={
                'verbose_name': 'Actualité',
                'verbose_name_plural': 'Actualités',
                'ordering': ['-date_publication'],
            },
        ),
        migrations.DeleteModel(
            name='News',
        ),
    ]
