# Generated by Django 5.2.14 on 2026-05-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_actualite_delete_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
