# Generated by Django 5.2.14 on 2026-05-19 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_actualite_slug_alter_actualite_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
